// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5BvjNcx6pzw8KkA9KgduoYxAuJPb6oxQ',
    appId: '1:611377024857:web:37409e2c91e338c5b70648',
    messagingSenderId: '611377024857',
    projectId: 'face-detection-app-b4724',
    authDomain: 'face-detection-app-b4724.firebaseapp.com',
    storageBucket: 'face-detection-app-b4724.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4t7y6D9E4HPYwN1MmyiIp1T1DMoe0UG0',
    appId: '1:611377024857:android:69ab357f0294ee49b70648',
    messagingSenderId: '611377024857',
    projectId: 'face-detection-app-b4724',
    storageBucket: 'face-detection-app-b4724.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHJ3LWzVqLFqquQWynQkF6u2RLQ62MIzc',
    appId: '1:611377024857:ios:ff8e65e20dcd81c4b70648',
    messagingSenderId: '611377024857',
    projectId: 'face-detection-app-b4724',
    storageBucket: 'face-detection-app-b4724.firebasestorage.app',
    iosBundleId: 'com.example.faceRecognitionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHJ3LWzVqLFqquQWynQkF6u2RLQ62MIzc',
    appId: '1:611377024857:ios:ff8e65e20dcd81c4b70648',
    messagingSenderId: '611377024857',
    projectId: 'face-detection-app-b4724',
    storageBucket: 'face-detection-app-b4724.firebasestorage.app',
    iosBundleId: 'com.example.faceRecognitionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5BvjNcx6pzw8KkA9KgduoYxAuJPb6oxQ',
    appId: '1:611377024857:web:d8c67aa14f3545bab70648',
    messagingSenderId: '611377024857',
    projectId: 'face-detection-app-b4724',
    authDomain: 'face-detection-app-b4724.firebaseapp.com',
    storageBucket: 'face-detection-app-b4724.firebasestorage.app',
  );
}
